version: '3'

services:

  lydia-webshop-mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:-1234}
      - MYSQL_DATABASE=${DATABASE_NAME:-lydia_webshop}
      - MYSQL_USER=${DATABASE_USERNAME:-sa}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:-1234}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  lydia-webshop-backend:
    image: 'lydia-webshop-backend'
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:mysql://lydia-webshop-mysqldb:3306/lydia_webshop
      - spring.datasource.username=${DATABASE_USERNAME:-sa}
      - spring.datasource.password=${DATABASE_PASSWORD:-1234}
      - spring.jpa.hibernate.ddl-auto=create
      - frontend.url=http://localhost
    depends_on:
      lydia-webshop-mysqldb:
        condition: service_healthy
  
  lydia-webshop-frontend:
    image: 'lydia-webshop-frontend'
    build:
      context: 'lydia-webshop-frontend'
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'
#     Port 80 is used with nginx docker base image
#     If you want to use the node alpine base image, then use port 3000 like this:
#      - '3000:3000'
