spring:

  profiles:
      active: development

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/lydia_webshop}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:1234}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}
